# Generated by Django 3.1 on 2020-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200807_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactform',
        ),
    ]
